
baseline:                   ''          # baseline (without extension) of plink files
threads:                    8
memory:                     16384       # Memory, in MB, allowed to plink invocations
sex_discrepancy_discard:    True        # after imputation, remove sex discrepancies or not
MAF_threshold:              0.01
rm_tmp:                     True         # remove temporary files while processing (Y/n)  

# Steps selection
Missingness:                True
Sex_discrepancy:            True
Autos_MAF:                  True
Hardy-Weinberg:             True
Heterozygosity_rate:        True
Cryptic_relatedness:        True
Population_filtering:       True
MDS_covariates:             True

# Optionals
population_file:            '../1kG'
population_panel:           '../1kG.ALL.panel'
inferior_threshold_MDS_1:   '0.05'
superior_threshold_MDS_1:   '0.17'
inferior_threshold_MDS_2:   '0.00'
superior_threshold_MDS_2:   '0.12'

